apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-posts
  namespace: nietylkoquizy
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: backend-posts
  template:
    metadata:
      labels:
        io.kompose.service: backend-posts
    spec:
      containers:
        - name: backend-posts
          image: stadnicka/backend-posts:k8s
          args:
            - python
            - -m
            - flask
            - run
            - --host=0.0.0.0
            - --port=5001
          ports:
            - containerPort: 5001
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_DEBUG
              value: "1"
            - name: FLASK_ENV
              value: development
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: quizdb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql-root-password
            - name: KEYCLOAK_CLIENT_ID
              value: NieTylkoQuizyClient
            - name: KEYCLOAK_REALM
              value: NieTylkoQuizy
            - name: KEYCLOAK_URL
              value: http://keycloak:8080
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
