apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-posts
  namespace: nietylkoquizy
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: backend-posts
  template:
    metadata:
      labels:
        io.kompose.service: backend-posts
    spec:
      containers:
        - name: backend-posts
          image: stadnicka/backend-posts:latest
          ports:
            - containerPort: 5001
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_DEBUG
              value: "1"
            - name: FLASK_ENV
              value: development
            - name: MYSQL_HOST
              value: mysql  # Bezpośrednio nazwa usługi
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: quizdb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql-root-password
            - name: KEYCLOAK_CLIENT_ID
              value: NieTylkoQuizyClient
            - name: KEYCLOAK_REALM
              value: NieTylkoQuizy
            - name: KEYCLOAK_URL
              value: http://keycloak:8080
