apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: backend-users
  name: backend-users
  namespace: nietylkoquizy
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: backend-users
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: backend-users
    spec:
      containers:
        - name: backend-users
          image: stadnicka/backend-users:k8s
          args:
            - python
            - -m
            - uvicorn
            - app:app
            - --host
            - 0.0.0.0
            - --port
            - "5002"
          ports:
            - containerPort: 5002
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: quizdb
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql-root-password
            - name: DB_USER
              value: root
            - name: KEYCLOAK_CLIENT_ID
              value: NieTylkoQuizyClient
            - name: KEYCLOAK_REALM
              value: NieTylkoQuizy
            - name: KEYCLOAK_URL
              value: http://keycloak:8080
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
