version: '3.9'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quizdb

    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


    ports:
      - "3306:3306"
    networks:
      - quiz-net

  backend-posts:
    build: ./backend-posts
    volumes:
      - ./backend-posts:/app
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DB: quizdb
      FLASK_ENV: development
      FLASK_APP: app.py
      FLASK_DEBUG: 1
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - quiz-net
    restart: unless-stopped

  backend-users:
    build: ./backend-users
    ports:
      - "5002:5002"
    networks:
      - quiz-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    command: npm run dev
    depends_on:
      - backend-posts
      - backend-users
    networks:
      - quiz-net

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"
    networks:
      - quiz-net

volumes:
  mysql_data:
  keycloak_data:

networks:
  quiz-net:
