# version: '3.9'
services:
  mysql:
    image: mysql:8
    # environment:
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quiz-net

  backend-posts:
    image: stadnicka/backend-posts:latest
    volumes:
      - ./backend-posts:/app
    ports:
      - "${BACKEND_POSTS_PORT}:5001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER_POSTS}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_POSTS}
      MYSQL_DB: ${MYSQL_DATABASE}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: ${FLASK_APP}
      FLASK_DEBUG: ${FLASK_DEBUG}
    command: python -m flask run --host=0.0.0.0 --port=5001
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5001/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - quiz-net
    restart: unless-stopped

  backend-users:
    image: stadnicka/backend-users:latest
    command: python -m uvicorn app:app --host 0.0.0.0 --port 5002
    ports:
      - "${BACKEND_USERS_PORT}:5002"
    environment:
      - DB_USER=${MYSQL_USER_USERS}
      - DB_PASSWORD=${MYSQL_PASSWORD_USERS}
      - DB_HOST=${MYSQL_HOST}
      - DB_NAME=${MYSQL_DATABASE}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5002/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - quiz-net

  frontend:
    image: stadnicka/frontend:latest
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
    command: npm run dev
    depends_on:
      backend-posts:
        condition: service_healthy
      backend-users:
        condition: service_healthy
    networks:
      - quiz-net

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL_HOST=${MYSQL_HOST}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/8080' || exit 1"]
      interval: 30s
      timeout: 10s      
      retries: 5
      start_period: 90s 
    networks:
      - quiz-net

volumes:
  mysql_data:
  keycloak_data:

networks:
  quiz-net: