apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: nietylkoquizy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "hostpath"
  resources:
    requests:
      storage: 1Gi