apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nietylkoquizy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - name: frontend
          image: stadnicka/frontend:k8s
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_POSTS_URL
              value: "http://localhost:5001"  # ← ZMIEŃ NA LOCALHOST
            - name: NEXT_PUBLIC_BACKEND_USERS_URL
              value: "http://localhost:5002"  # ← ZMIEŃ NA LOCALHOST
            - name: NEXT_PUBLIC_KEYCLOAK_URL
              value: "http://localhost:8080"  # ← ZMIEŃ NA LOCALHOST
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
