apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nietylkoquizy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - name: frontend
          image: stadnicka/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_POSTS_URL
              value: "http://backend-posts:5001"
            - name: NEXT_PUBLIC_BACKEND_USERS_URL
              value: "http://backend-users:5002"
            - name: NEXT_PUBLIC_KEYCLOAK_URL
              value: "http://keycloak:8080"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
