apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: nietylkoquizy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
