apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend-lb
  namespace: nietylkoquizy
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-posts-lb
  namespace: nietylkoquizy
spec:
  type: LoadBalancer
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: backend-posts
---
apiVersion: v1
kind: Service
metadata:
  name: backend-users-lb
  namespace: nietylkoquizy
spec:
  type: LoadBalancer
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: backend-users
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-lb
  namespace: nietylkoquizy
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: keycloak
